'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Fallout76Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Fallout_76() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Fallout_76", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ScreenSplatter]
        '''bBloodSplatterEnabled = 1
        '''
        '''[Display]
        '''bDynamicObjectQueryManager = 1
        '''bMultiThreadedAccumulation = 1
        '''bMultiThreadedRenderingUNP = 1
        '''fDecalLOD0 = 8192
        '''fSAORadius = 108.2
        '''fSAOBias = 0.6
        '''fSunUpdateThreshold = 0.5f
        '''bFull Screen = 1
        '''bBorderless = 0
        '''
        '''[HairLighting]
        '''fHairPrimSpecScale = 0.04
        '''fHairPrimSpecPow = 388
        '''fHairPrimSpecShift = 1.0
        '''fHairSecSpecScale = 0.89
        '''fHairSecSpecPow = 98
        '''fHairSecSpecShift = 1.2
        '''
        '''[MapMenu]
        '''uLockedObjectMapLOD = 16
        '''uLockedTerrainLOD = 32
        '''
        '''[Grass] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property High() As String
            Get
                Return ResourceManager.GetString("High", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=120000.0000
        '''fDirShadowDistance=120000.0000
        '''iShadowMapResolution=2048
        '''uiShadowFilter=3
        '''uiOrthoShadowFilter=3
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=4
        '''iMaxDecalsPerFrame=100
        '''iMaxSkinDecalsPerFrame=25
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=3
        '''iVolumetricLightingTextureQuality=2
        '''iLocation X=0
        '''iLocation Y=0
        '''bFull Screen=1
        '''bBorderless=0
        '''iGraphicPreset=3
        '''fShadowBiasScale=1.0000
        '''iDirShadowSplits=4
        '''uShadowExpirationMS=5000
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HighPrefs() As String
            Get
                Return ResourceManager.GetString("HighPrefs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ScreenSplatter]
        '''bBloodSplatterEnabled = 1
        '''
        '''[Display]
        '''bDynamicObjectQueryManager = 1
        '''bMultiThreadedAccumulation = 1
        '''bMultiThreadedRenderingUNP = 1
        '''fDecalLOD0 = 8192
        '''fSAORadius = 108.2
        '''fSAOBias = 0.6
        '''fSunUpdateThreshold = 0.5f
        '''bFull Screen = 1
        '''bBorderless = 0
        '''
        '''[HairLighting]
        '''fHairPrimSpecScale = 0.04
        '''fHairPrimSpecPow = 388
        '''fHairPrimSpecShift = 1.0
        '''fHairSecSpecScale = 0.89
        '''fHairSecSpecPow = 98
        '''fHairSecSpecShift = 1.2
        '''
        '''[Audio]
        '''bEnableAudio = 1
        '''
        '''[MapMenu]
        '''uLockedObjectMapLOD = 16
        '''uLoc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Low() As String
            Get
                Return ResourceManager.GetString("Low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=0
        '''fShadowDistance=60000.0000
        '''fDirShadowDistance=60000.0000
        '''iShadowMapResolution=1024
        '''uiShadowFilter=1
        '''uiOrthoShadowFilter=1
        '''fBlendSplitDirShadow=0.0000
        '''iMaxFocusShadows=0
        '''iMaxDecalsPerFrame=0
        '''iMaxSkinDecalsPerFrame=0
        '''bVolumetricLightingEnable=0
        '''bSAOEnable=1
        '''uWaterShadowFilter=1
        '''iVolumetricLightingTextureQuality=0
        '''iLocation X=0
        '''iLocation Y=0
        '''bFull Screen=1
        '''bBorderless=0
        '''iGraphicPreset=1
        '''fShadowBiasScale=1.0000
        '''iDirShadowSplits=4
        '''uShadowExpirationMS=5000
        '''uPointL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LowPrefs() As String
            Get
                Return ResourceManager.GetString("LowPrefs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ScreenSplatter]
        '''bBloodSplatterEnabled = 1
        '''
        '''[Display]
        '''bDynamicObjectQueryManager = 1
        '''bMultiThreadedAccumulation = 1
        '''bMultiThreadedRenderingUNP = 1
        '''fDecalLOD0 = 8192
        '''fSAORadius = 108.2
        '''fSAOBias = 0.6
        '''fSunUpdateThreshold = 0.5f
        '''bFull Screen = 1
        '''bBorderless = 0
        '''
        '''[HairLighting]
        '''fHairPrimSpecScale = 0.04
        '''fHairPrimSpecPow = 388
        '''fHairPrimSpecShift = 1.0
        '''fHairSecSpecScale = 0.89
        '''fHairSecSpecPow = 98
        '''fHairSecSpecShift = 1.2
        '''
        '''[Audio]
        '''bEnableAudio = 1
        '''
        '''[MapMenu]
        '''uLockedObjectMapLOD = 16
        '''uLoc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Medium() As String
            Get
                Return ResourceManager.GetString("Medium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=90000.0000
        '''fDirShadowDistance=90000.0000
        '''iShadowMapResolution=2048
        '''uiShadowFilter=2
        '''uiOrthoShadowFilter=2
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=1
        '''iMaxDecalsPerFrame=10
        '''iMaxSkinDecalsPerFrame=3
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=2
        '''iVolumetricLightingTextureQuality=1
        '''iLocation X=0
        '''iLocation Y=0
        '''bFull Screen=1
        '''bBorderless=0
        '''iGraphicPreset=2
        '''fShadowBiasScale=1.0000
        '''iDirShadowSplits=4
        '''uShadowExpirationMS=5000
        '''uPoi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MediumPrefs() As String
            Get
                Return ResourceManager.GetString("MediumPrefs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property optionslit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("optionslit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property support() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("support", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supportlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supportlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [ScreenSplatter]
        '''bBloodSplatterEnabled = 1
        '''
        '''[Display]
        '''bDynamicObjectQueryManager = 1
        '''bMultiThreadedAccumulation = 1
        '''bMultiThreadedRenderingUNP = 1
        '''fDecalLOD0 = 8192
        '''fSAORadius = 108.2
        '''fSAOBias = 0.6
        '''fSunUpdateThreshold = 0.5f
        '''bFull Screen = 1
        '''bBorderless = 0
        '''
        '''[HairLighting]
        '''fHairPrimSpecScale = 0.04
        '''fHairPrimSpecPow = 388
        '''fHairPrimSpecShift = 1.0
        '''fHairSecSpecScale = 0.89
        '''fHairSecSpecPow = 98
        '''fHairSecSpecShift = 1.2
        '''
        '''[Audio]
        '''bEnableAudio = 1
        '''
        '''[MapMenu]
        '''uLockedObjectMapLOD = 16
        '''uLoc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ultra() As String
            Get
                Return ResourceManager.GetString("Ultra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=150000.0000
        '''fDirShadowDistance=150000.0000
        '''iShadowMapResolution=2048
        '''uiShadowFilter=3
        '''uiOrthoShadowFilter=3
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=4
        '''iMaxDecalsPerFrame=100
        '''iMaxSkinDecalsPerFrame=25
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=3
        '''iVolumetricLightingTextureQuality=2
        '''iLocation X=0
        '''iLocation Y=0
        '''bFull Screen=1
        '''bBorderless=0
        '''iGraphicPreset=4
        '''fShadowBiasScale=1.0000
        '''iDirShadowSplits=4
        '''uShadowExpirationMS=5000
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UltraPrefs() As String
            Get
                Return ResourceManager.GetString("UltraPrefs", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
