'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Fallout76Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Fallout_76() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Fallout_76", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=120000.0
        '''fDirShadowDistance=120000.0
        '''iShadowMapResolution=2048.0
        '''uiShadowFilter=3
        '''uiOrthoShadowFilter=3
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=4
        '''iMaxDecalsPerFrame=100
        '''iMaxSkinDecalsPerFrame=25
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=3
        '''iVolumetricLightingTextureQuality=2
        '''
        '''[Decals]
        '''bDecals=1
        '''bSkinnedDecals=1
        '''uMaxDecals=250
        '''uMaxSkinDecals=50
        '''
        '''[TerrainManager]
        '''fBlockMaximumDistance=180000.0000
        '''fBlockLevel2Distance=11 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property High() As String
            Get
                Return ResourceManager.GetString("High", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=0
        '''fShadowDistance=60000.0
        '''fDirShadowDistance=60000.0
        '''iShadowMapResolution=1024
        '''uiShadowFilter=1
        '''uiOrthoShadowFilter=1
        '''fBlendSplitDirShadow=0.0000
        '''iMaxFocusShadows=0
        '''iMaxDecalsPerFrame=0
        '''iMaxSkinDecalsPerFrame=0
        '''bVolumetricLightingEnable=0
        '''bSAOEnable=1
        '''uWaterShadowFilter=1
        '''iVolumetricLightingTextureQuality=0
        '''
        '''[Decals]
        '''bDecals=0
        '''bSkinnedDecals=0
        '''uMaxDecals=0
        '''uMaxSkinDecals=0
        '''
        '''[TerrainManager]
        '''fBlockMaximumDistance=100000.0000
        '''fBlockLevel2Distance=75000.0000
        '''fB [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Low() As String
            Get
                Return ResourceManager.GetString("Low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=90000.0
        '''fDirShadowDistance=90000.0
        '''iShadowMapResolution=2048.0
        '''uiShadowFilter=2
        '''uiOrthoShadowFilter=2
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=1
        '''iMaxDecalsPerFrame=10
        '''iMaxSkinDecalsPerFrame=3
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=2
        '''iVolumetricLightingTextureQuality=1
        '''
        '''[Decals]
        '''bDecals=1
        '''bSkinnedDecals=1
        '''uMaxDecals=100
        '''uMaxSkinDecals=35
        '''
        '''[TerrainManager]
        '''fBlockMaximumDistance=100000.0000
        '''fBlockLevel2Distance=80000. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Medium() As String
            Get
                Return ResourceManager.GetString("Medium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property optionslit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("optionslit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property playlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property support() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("support", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supportlit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supportlit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Display]
        '''iMaxAnisotropy=16
        '''fShadowDistance=150000.0
        '''fDirShadowDistance=150000.0
        '''iShadowMapResolution=2048.0
        '''uiShadowFilter=3
        '''uiOrthoShadowFilter=3
        '''fBlendSplitDirShadow=48.0000
        '''iMaxFocusShadows=4
        '''iMaxDecalsPerFrame=100
        '''iMaxSkinDecalsPerFrame=25
        '''bVolumetricLightingEnable=1
        '''bSAOEnable=1
        '''uWaterShadowFilter=3
        '''iVolumetricLightingTextureQuality=2
        '''
        '''[Decals]
        '''bDecals=1
        '''bSkinnedDecals=1
        '''uMaxDecals=1000
        '''uMaxSkinDecals=100
        '''
        '''[TerrainManager]
        '''fBlockMaximumDistance=250000.0000
        '''fBlockLevel2Distance= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ultra() As String
            Get
                Return ResourceManager.GetString("Ultra", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
